# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('title', 'slug')]),
        ),
    ]
