# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 18:41
from __future__ import unicode_literals

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20161228_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=8, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=8, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=8, max_length=8, unique=True),
        ),
    ]
