# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 19:29
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_userdocumentfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=simplemde.fields.SimpleMDEField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=simplemde.fields.SimpleMDEField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=simplemde.fields.SimpleMDEField(),
        ),
    ]
