# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20161229_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
